server:
  #定义端口号
  port: 8082
#eureka:
#  client:
#    fetch-registry: true
#  service-url:
#    defaultZone: http://localhost:8761/eureka
#  #服务注册中心实例的主机名
#  instance:
#    hostname: 127.0.0.1
#    prefer-ip-address: true
#    instance-id: 127.0.0.1:${server.port}